### ISSUE TITLE
Not working on 0.27.0

### ISSUE THREAD

**Issue by JanHolger** [straight-shoota/crinja#19]
On the current version of crystal (0.27.0) its throwing many errors on compilation for us.

Last error is always:
```
in /usr/share/crystal/src/indexable.cr:188: abstract `def Indexable(T)#unsafe_fetch(index : Int)` must be implemented by Crinja::Tuple
yield unsafe_fetch(i)
```

Seems to be related to your last commit.

**Comment by straight-shoota** [comment]
Thanks for letting me know!

The spec suite compiles with `0.27.0` and it even Crystal master (see [nightly CI](https://circleci.com/gh/straight-shoota/crinja/224) - the full CI run only fails because of a breaking change in the formatter).

The last commit 0e2b3c6555efef5bc4e66561f679c1b6fe5efd46 is supposed to add support for 0.27.0 while 
keeping compatible with 0.26.1.

Maybe you're hitting an untested path? Can you share a reproducible example of what you're trying to do?

And to rule out any possibilities: the commit hash printed by `crystal --version` should be c9d1eef8f for 0.27.0 release. Is that correct?
