### ISSUE TITLE
set variable to new value is ignored?

### ISSUE THREAD

**Issue by petr-fischer** [straight-shoota/crinja#21]
Example:
```jinja2
...
        {% set active = "active" %}
        {% set cnt = 1 %}
        {% for photo in photos %}
        <div class="carousel-item {{ active }} {{ cnt }}">
            <img src="{{ photo }}" class="d-block w-100">
        </div>
        {% set active = "" %}
        {% set cnt = cnt + 1 %}
        {% endfor %}
...
```

Variables "active" and "cnt" are still the same - what's wrong?

Generated output:
```html
        <div class="carousel-item active 1">
            <img src="photos/camp/foto1.jpg" class="d-block w-100">
        </div>
        
        <div class="carousel-item active 1">
            <img src="photos/camp/foto14.jpg" class="d-block w-100">
        </div>
        
        <div class="carousel-item active 1">
            <img src="photos/camp/foto2.jpg" class="d-block w-100">
        </div>
....
```

**Comment by straight-shoota** [comment]
This is currently expected behaviour. Setting the value is not ignored, but limited to the current scope and a for loop is a different scope. That's how Jinja2 works and Crinja tries to stay as close as possible.
We could however decide to change this in Crinja, but I'd like to avoid such breaking changes.

There are some workarounds for implementing such kind of logic which don't rely on setting a variable but changing it's value. A counter for example could be an array and you add an element for each iteration. The length of the array represent the counter value.

But your example can easily be solved using `loop.index` as counter and `loop.first` for active check.

See [Jinja2 Template Designer Documentation](http://jinja.pocoo.org/docs/2.10/templates/) for details on these special loop variables and the scoping behavior.

**Comment by petr-fischer** [comment]
Oh **thanks** for the point to the special loop variables!
