### ISSUE TITLE
type error: can't wrap MyObject in Crinja::Value

### ISSUE THREAD

**Issue by petr-fischer** [straight-shoota/crinja#22]
Hello, what this error means? I have Array of MyObject class instances in template bindings and I want to access the Array of MyObject in template like:

```
{% for obj in objs %}
...
   {{ obj.some_property }}
...
{% endblock %}
```

MyObject is my own class/struct with proper getters.

Thanks!

**Comment by straight-shoota** [comment]
Crystal currently can't use a generic `Object` type for an instance variable. But Crinja needs to store the values you're binding to variables. The most common stdlib types are directly known to Crinja and you can simply assign them as Crinja values. That works out of the box. But Crinja can't know the custom data types defined in your code.
So the trick is to include `Crinja::Object` in any data type that is supposed to be exposed to Crinja. Crinja can store `Crinja::Object` in instance variables, so this works nicely, but it requires a slight modification to your data types.

Example:
```cr
@[Crinja::Attributes]
class MyObject
  include Crinja::Object::Auto

  def some_property
    "property_value"
  end
end
```
`Crinja::Object::Auto` includes `Crinja::Object` to enable the data type for Crinja values, but together with `@[Crinja::Attributes]` also exposes public properties (like `some_property`) to be accessible from Crinja. Otherwise having an object of that type in the template would not be of much use.

More detailed explanation: https://github.com/straight-shoota/crinja/blob/master/playground/objects.md

**Comment by petr-fischer** [comment]
I completely missed playgrounds. Maybe you can add "objects" playground also to the main doc page here: https://github.com/straight-shoota/crinja - playground "features" already exist as chapter "Custom features" on this page. Thanks very much for the explanation - everything works!

**Comment by straight-shoota** [comment]
Yes, using workbooks in the playground is a very much hidden feature :D But great for embedding example code.
